apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "postgres-spacex.fullname" . }}-script
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "postgres-spacex.labels" . | nindent 4 }}
data:
  init-sql.sh: |
{{ tpl (.Files.Get "files/init-sql.sh") . | indent 4 }} 