apiVersion: v1
kind: ConfigMap
metadata:
  name: airflow-config
  namespace: {{ .Release.Namespace }}
data:
  AIRFLOW__CORE__EXECUTOR: "LocalExecutor"
  AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: "postgresql+psycopg2://{{ .Values.database.user }}:{{ .Values.database.password }}@{{ .Values.database.host }}.{{ .Values.database.namespace }}.svc.cluster.local:{{ .Values.database.port }}/{{ .Values.database.name }}"
  AIRFLOW__CORE__FERNET_KEY: ""
  AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: "true"
  AIRFLOW__CORE__LOAD_EXAMPLES: "false"
  AIRFLOW__API__AUTH_BACKENDS: "airflow.api.auth.backend.basic_auth"
  POSTGRES_HOST: "{{ .Values.env.POSTGRES_HOST }}"
  POSTGRES_DB: "{{ .Values.env.POSTGRES_DB }}"
  POSTGRES_USER: "{{ .Values.env.POSTGRES_USER }}"
  POSTGRES_PASSWORD: "{{ .Values.env.POSTGRES_PASSWORD }}" 