apiVersion: v1
kind: Service
metadata:
  name: airflow-webserver
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: airflow-webserver
  ports:
  - port: {{ .Values.airflow.webserver.port }}
    targetPort: {{ .Values.airflow.webserver.port }}
    nodePort: {{ .Values.airflow.webserver.service.nodePort }}
  type: {{ .Values.airflow.webserver.service.type }}